services:
    _instanceof:
        Ergonode\Value\Domain\Service\ValueUpdateStrategyInterface:
            tags: ['ergonode.value_update_strategy']
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ergonode\Value\Domain\:
        resource: '../../Domain/*'
        exclude: '../../Domain/{Entity,ValueObject}'

    Ergonode\Value\Domain\Service\ValueManipulationService:
        - !tagged 'ergonode.value_update_strategy'

    Ergonode\Value\Infrastructure\JMS\Serializer\Handler\:
        resource: '../../Infrastructure/JMS/Serializer/Handler/*'
        tags: ['jms_serializer.subscribing_handler']

    Ergonode\Value\Infrastructure\JMS\Serializer\Handler\ValueInterfaceHandler:
        calls:
            - ['set', ['Ergonode\Value\Domain\ValueObject\StringValue']]
            - ['set', ['Ergonode\Value\Domain\ValueObject\StringCollectionValue']]
            - ['set', ['Ergonode\Value\Domain\ValueObject\TranslatableStringValue']]
            - ['set', ['Ergonode\Value\Domain\ValueObject\TranslatableCollectionValue']]
